#!/usr/bin/env bash
# Concatenate core + all case files into dist/full.md, for tools with no on-demand loading.
# Front matter of each file is stripped.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/dist/full.md"
mkdir -p "$root/dist"

strip_front_matter() {
  awk 'NR==1 && $0=="---" {skip=1; next} skip && $0=="---" {skip=0; next} !skip' "$1"
}

{
  echo "<!-- Generated by scripts/build-full.sh. Do not edit. -->"
  echo
  strip_front_matter "$root/core/core.md"
  for f in "$root"/cases/*.md; do
    echo
    echo "---"
    echo
    strip_front_matter "$f"
  done
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines)"
